<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.3.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.3.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Articles.Abstractions\Articles.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\buildingBlocks\Blocks.Core\Blocks.Core.csproj" />
    <ProjectReference Include="..\..\..\buildingBlocks\Blocks.Exceptions\Blocks.Exceptions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Blocks.Redis\Blocks.Redis.csproj" />
    <ProjectReference Include="..\Journals.Domain\Journals.Domain.csproj" />
  </ItemGroup>

</Project>
